apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: junior-role-production
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"] # Tüm kaynaklara izin ver
  verbs: ["get", "list"] # okuma ve listeleme

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: junior-role-production-binding
  namespace: production
subjects:
- kind: Group
  name: junior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: junior-role-production
  apiGroup: rbac.authorization.k8s.io