apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: senior-cluster-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list"] # Sadece okuma ve listeleme izinleri

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: senior-cluster-role-binding
subjects:
- kind: Group
  name: senior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: senior-cluster-role
  apiGroup: rbac.authorization.k8s.io
